services:
  starbound:
    build: .
    container_name: starbound
    ports:
      - "21025:21025/tcp"
      - "21025:21025/udp"
      - "21026:21026/tcp"
    volumes:
      - /mnt/starbound-dedicated:/opt/starbound-dedicated
